const routes = [
  {
    path: "/",
    component: () => import("layouts/client/HomeLayout.vue"),
  },
  {
    path: "/admin",
    component: () => import("layouts/admin/LoginLayout.vue"),
    name: "admin",
    children: [
      {
        path: "",
        component: () => import("pages/admin/LoginPage.vue"),
        name: "login",
        meta: { private: false },
      },
      {
        path: "/forgot_password",
        component: () => import("pages/admin/ForgotPasswordPage.vue"),
        name: "forgot",
        meta: { private: false },
      },
      {
        path: "/change_password",
        component: () => import("pages/admin/ChangePasswordPage.vue"),
        name: "changePassword",
        meta: { private: false },
      },
    ],
  },
  {
    path: "/administracion",
    component: () => import("layouts/admin/AdminHomeLayout.vue"),
    name: "adminHome",
    meta: {
      private: true,
      permissions: [
        "04",
        "03",
        "37",
        "25",
        "27",
        "28",
        "26",
        "21",
        "24",
        "23",
        "22",
        "38",
        "39",
        "19",
        "20",
        "17",
        "18",
        "15",
        "16",
        "13",
        "14",
        "12",
        "11",
        "40",
        "41",
        "42",
        "05",
        "06",
        "29",
        "30",
        "32",
        "31",
        "02",
        "01",
        "33",
        "34",
        "35",
        "36",
        "08",
        "07",
        "09",
        "10",
      ],
    },
    children: [
      {
        path: "/obras",
        component: () => import("pages/admin/LiteraryWorksPage.vue"),
        name: "adminLiteraryWorks",
        meta: { private: true, permissions: ["04", "03"] },
      },
      {
        path: "/usuarios-obras",
        component: () => import("pages/admin/UsuariosObraPage.vue"),
        name: "adminUsuariosObra",
        meta: { private: true, permissions: ["37", "38"] },
      },
      {
        path: "/publico-objetivo-audiolibro",
        component: () => import("pages/admin/PublicosAudiolibroPage.vue"),
        name: "adminPublicosA",
        meta: { private: true, permissions: ["39", "40"] },
      },
      {
        path: "/publico-objetivo-ebook",
        component: () => import("pages/admin/PublicosEbookPage.vue"),
        name: "adminPublicosE",
        meta: { private: true, permissions: ["41", "42"] },
      },
      {
        path: "/autores",
        component: () => import("pages/admin/AuthorsPage.vue"),
        name: "adminAuthors",
        meta: { private: true, permissions: ["05", "06"] },
      },
      {
        path: "/interfaz/cabecera",
        component: () => import("src/pages/admin/HeaderInterfacePage.vue"),
        name: "adminHeaderInterface",
        meta: { private: true, permissions: ["29", "30"] },
      },
      {
        path: "/interfaz/carrusel",
        component: () => import("pages/admin/CarouselInterfacePage.vue"),
        name: "adminCarouselInterface",
        meta: { private: true, permissions: ["32", "31"] },
      },
      {
        path: "/expedientes",
        component: () => import("pages/admin/ExpedientsPage.vue"),
        name: "adminExpedients",
        meta: { private: true, permissions: ["02", "01"] },
      },
      {
        path: "/usuarios",
        component: () => import("pages/admin/UsersPage.vue"),
        name: "adminUsers",
        meta: { private: true, permissions: ["33", "34"] },
      },
      {
        path: "/roles",
        component: () => import("pages/admin/RolesPage.vue"),
        name: "adminRoles",
        meta: { private: true, permissions: ["35", "36"] },
      },
      {
        path: "/tematicas",
        component: () => import("pages/admin/TematicsPage.vue"),
        name: "adminTematics",
        meta: { private: true, permissions: ["08", "07"] },
      },
      {
        path: "/generos",
        component: () => import("pages/admin/GendersPage.vue"),
        name: "adminGenders",
        meta: { private: true, permissions: ["09", "10"] },
      },
      {
        path: "/grupos",
        component: () => import("pages/admin/GroupsPage.vue"),
        name: "adminGroups",
        meta: { private: true, permissions: ["12", "11"] },
      },
      {
        path: "/tiposTrabajo",
        component: () => import("pages/admin/TypeWorksPage.vue"),
        name: "adminTypeWorks",
        meta: { private: true, permissions: ["13", "14"] },
      },
      {
        path: "/clasificaciones",
        component: () => import("pages/admin/ClasificationsPage.vue"),
        name: "adminClasifications",
        meta: { private: true, permissions: ["15", "16"] },
      },
      {
        path: "/clasificadores",
        component: () => import("pages/admin/ClasificatorsPage.vue"),
        name: "adminClasificators",
        meta: { private: true, permissions: ["17", "18"] },
      },
      {
        path: "/idiomas",
        component: () => import("pages/admin/LanguagesPage.vue"),
        name: "adminLanguages",
        meta: { private: true, permissions: ["19", "20"] },
      },
      {
        path: "/tiposLibro",
        component: () => import("pages/admin/TypeBooksPage.vue"),
        name: "adminTypeBooks",
        meta: { private: true, permissions: ["21", "22"] },
      },
      {
        path: "/papeles",
        component: () => import("pages/admin/PapersPage.vue"),
        name: "adminPapers",
        meta: { private: true, permissions: ["24", "23"] },
      },
      {
        path: "/cartulinas",
        component: () => import("pages/admin/CardBoardsPage.vue"),
        name: "adminCardBoards",
        meta: { private: true, permissions: ["25", "26"] },
      },
      {
        path: "/lugaresVenta",
        component: () => import("pages/admin/SellPlacesPage.vue"),
        name: "adminSellPlaces",
        meta: { private: true, permissions: ["27", "28"] },
      },
    ],
  },

  // Always leave this as last one,
  // but you can also remove it
  {
    path: "/:catchAll(.*)*",
    component: () => import("pages/client/ErrorNotFound.vue"),
  },
];

export default routes;
